# @package _global_
defaults:
  - /unf
  - override /net@model.net: lgatr
  - override /dataset: wwbb
  - _self_

data:
  on_gpu: false
  
dataset:
  reader:
    path: '/ptmp/mpp/mjosef/data_files/WbWb_files/bulk_region/converted_files/'
    num: null
  process:
    _target_: src.datasets.WWbbProcess

model:
  net:
    backbone:
      in_v_channels: 1
      in_s_channels: 4 # one hot pid
      hidden_v_channels: 8
      hidden_s_channels: 32
      num_blocks: 4
      num_heads: 4
      compile: True
  
training:
  lr: 0.001
  batch_size: 2048
  optimizer:
    warmup_steps: 5000
    weight_decay: 0.0
