run_name: ???
experiment: ???
train: True
evaluate: True
plot: True

use_gpu: True
device: 3
use_tf32: True
use_amp: False
num_cpus: 16
dry_run: False
submit: False
run_dir: runs
prev_exp_dir: null
atlas_style: true

num_bnn_samples: 10

data:
  num: null
  val_frac: 0.05
  test_frac: 0.35
  on_gpu: True

training:
  epochs: 1
  lr: 1.e-3
  batch_size: 512
  test_batch_size: 4096
  optimizer:
    _target_: schedulefree.AdamWScheduleFree
    weight_decay: 0.
  scheduler: {}
  gradient_norm: null
  validate_freq: 1
  patience: null
  save_best_epoch: True
  save_freq: null
  warm_start: null
  warm_start_epoch: null
  use_tensorboard: True
  log_iters: 500

plotting:
  pagewidth: 14
  num_bins: 15

defaults:
  - cluster: slurm
  - dataset: gaussian
  - hydra
  - _self_
