defaults:
  - /default
  - /net@model.net: mlp
  - _self_

run_name: unfold_${dataset.name}
experiment: UnfoldingExperiment

prev_it_path: null

model:
  _target_: src.models.KernelUnfolder
  loss: mlc
  norm: l1
  joint_ensembling: false
  norm_target: false
  cls_path: /scratch/mjosef/Unfolding/aussie/runs/classify_wwbb/2026-07-17_10-15-44
  kernel_p: 2
  kernel_scale: 1


training:
  lr: 1e-3
  epochs: 500
  batch_size: 4096
  test_batch_size: ${training.batch_size}
  patience: 10
  optimizer:
    betas: [0.98, 0.999]

data:
  on_gpu: true
