defaults:
  - /default
  - /net@model.net: mlp
  - _self_

run_name: unfold_${dataset.name}
experiment: UnfoldingExperiment

prev_it_path: null

tunfold:
  enabled: true
  num_bins_truth: ${plotting.num_bins}
  reco_bin_factor: 2
  clip_negative: true

model:
  _target_: src.models.KernelUnfolder
  loss: mlc
  norm: l1
  joint_ensembling: false
  norm_target: false
  cls_path: /scratch/mjosef/Unfolding/aussie/runs/classify_wwbb_multi/2026-07-28_13-52-15
  kernel_p: 2
  kernel_scale: 1


training:
  lr: 1e-3
  epochs: 100
  batch_size: 4096
  test_batch_size: ${training.batch_size}
  patience: 30
  optimizer:
    betas: [0.98, 0.999]

data:
  on_gpu: true

uncertainty:
  enabled: true
  n_boot: 200
  seed: 0
  control_exp_dir: null
  distribution: lognormal
  lognormal_sigma: 1.0
