name: wwbb
reader:
  _target_: src.datasets.WWbbData.read
  path_sim: /scratch/mjosef/Unfolding/aussie/data/sim
  path_data: /scratch/mjosef/Unfolding/aussie/data/pseudodata
  #path_data: /scratch/mjosef/Unfolding/aussie/data/data
  max_jets: 3
  num_sim: 2000000
  num_data: 2000000
  normalize: false
  seed: 42
  include_tagging: false
process:
  _target_: src.datasets.WWbbProcess