name: zjet_corrected
reader:
  _target_: src.datasets.ZJetData.read
  path: /ptmp/mpp/mjosef/data_files
  correction_weights: /ptmp/mpp/mjosef/data_files/correction_weights_zjet.npy
process:
  _target_: src.datasets.ZJetProcess
  num_features: 6  