name: zjet_particle
reader:
  _target_: src.datasets.ZJetParticleData.read
  path: /ptmp/mpp/mjosef/data_files
  observables_path: /ptmp/mpp/mjosef/data_files
process:
  _target_: src.datasets.ZJetParticleProcess  
  num_features: 4