# @package _global_
defaults:
  - /cls
  - override /dataset: wwbb_multi
  - _self_
data:
  on_gpu: true

model:
  net:
    dim_in: ${dataset.process.num_features}
    dim_out: 1
    ensembled: 60

replica_bootstrap:
  enabled: true
  n_replicas: 60
  seed: 0
  distribution: lognormal
  lognormal_sigma: 1.0

training:
  batch_size: 1024
  optimizer:
    warmup_steps: 5000
    weight_decay: 0.0